// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs32jBsmxJA1lu5tOI-RIHaBBCsbRZ9G8',
    appId: '1:1069963301951:web:fe0b0ea3615debdfdd548a',
    messagingSenderId: '1069963301951',
    projectId: 'veltro-aberux',
    authDomain: 'veltro-aberux.firebaseapp.com',
    storageBucket: 'veltro-aberux.firebasestorage.app',
    measurementId: 'G-SL17V5NLX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-AwM1GOVqBeGlanMjsNAAR9jBrc7cFGE',
    appId: '1:1069963301951:android:e9b24aeed0465cbcdd548a',
    messagingSenderId: '1069963301951',
    projectId: 'veltro-aberux',
    storageBucket: 'veltro-aberux.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY0fZMexIZx6thizhrQb8e0xtFY5x9nBA',
    appId: '1:1069963301951:ios:7c96373a01dface4dd548a',
    messagingSenderId: '1069963301951',
    projectId: 'veltro-aberux',
    storageBucket: 'veltro-aberux.firebasestorage.app',
    iosBundleId: 'com.veltro.veltroMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY0fZMexIZx6thizhrQb8e0xtFY5x9nBA',
    appId: '1:1069963301951:ios:7c96373a01dface4dd548a',
    messagingSenderId: '1069963301951',
    projectId: 'veltro-aberux',
    storageBucket: 'veltro-aberux.firebasestorage.app',
    iosBundleId: 'com.veltro.veltroMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs32jBsmxJA1lu5tOI-RIHaBBCsbRZ9G8',
    appId: '1:1069963301951:web:04e64358c7903566dd548a',
    messagingSenderId: '1069963301951',
    projectId: 'veltro-aberux',
    authDomain: 'veltro-aberux.firebaseapp.com',
    storageBucket: 'veltro-aberux.firebasestorage.app',
    measurementId: 'G-9JD0P5GYB4',
  );
}
