spring.application.name=api-gateway
server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info

# JWT
jwt.secret=veltro-super-secret-key-that-is-long-enough-for-hmac-sha256
jwt.access-token-expiry=900000
jwt.refresh-token-expiry=86400000

# Routes
spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=user-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/users/**

spring.cloud.gateway.server.webmvc.routes[2].id=nfc-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/nfc/**

spring.cloud.gateway.server.webmvc.routes[3].id=subscription-service
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/subscriptions/**

spring.cloud.gateway.server.webmvc.routes[4].id=booking-courses
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/v1/courses/**

spring.cloud.gateway.server.webmvc.routes[5].id=booking-bookings
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/v1/bookings/**

spring.cloud.gateway.server.webmvc.routes[6].id=booking-attendance
spring.cloud.gateway.server.webmvc.routes[6].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/v1/attendance/**

spring.cloud.gateway.server.webmvc.routes[7].id=activity-service
spring.cloud.gateway.server.webmvc.routes[7].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/v1/activity/**