name: Veltro CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-all:
    name: Build All Services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: |
          chmod +x backend/eureka-server/mvnw
          chmod +x backend/api-gateway/mvnw
      
      - name: Make mvnw executable
        run: |
          chmod +x backend/eureka-server/mvnw
          chmod +x backend/api-gateway/mvnw
          chmod +x backend/auth-service/mvnw

      - name: Build and install common-lib
        working-directory: backend/common-lib
        run: mvn clean install

      - name: Build Eureka Server
        working-directory: backend/eureka-server
        run: ./mvnw clean package -DskipTests

      - name: Build API Gateway
        working-directory: backend/api-gateway
        run: ./mvnw clean package -DskipTests

      - name: Make auth-service mvnw executable
        run: chmod +x backend/auth-service/mvnw

      - name: Build and test Auth Service
        working-directory: backend/auth-service
        run: ./mvnw clean verify